gateway:
  loglevel: DEBUG
  prefix: /services/dask-gateway
  env:
  - name: MY_ENV
    value: My env
  - name: MY_CPU_REQUESTS
    valueFrom:
      resourceFieldRef:
        containerName: gateway
        resource: requests.cpu
  - name: MY_HOSTIP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  backend:
    scheduler:
      cores:
        request: 0.1
      memory:
        request: 256M

    worker:
      cores:
        request: 0.1
      memory:
        request: 256M

controller:
  loglevel: DEBUG
  completedClusterMaxAge: 60
  completedClusterCleanupPeriod: 30

traefik:
  loglevel: INFO
  service:
    ports:
      web:
        nodePort: 30200
